import { ManifestEntry } from "../types/manifest";
import { formatSize, formatDuration } from "./formatters";

interface LogSessionInfo {
  machineName: string;
  os: string;
  appVersion: string;
  sessionId: string;
  destinationPath: string; // <--- ADDED: Critical Context from Legacy Log
  startTime: number;
  endTime: number;
}

export function generateLogContent(
  session: LogSessionInfo,
  files: ManifestEntry[]
): string {
  // 1. Calculate Summary Metrics
  const totalBytes = files.reduce((acc, f) => acc + f.size_bytes, 0);
  const durationMs = session.endTime - session.startTime;
  const successCount = files.filter((f) => f.status === "verified").length;

  // 2. Format Header
  const dateStr = new Date(session.startTime).toLocaleDateString();
  const timeStr = new Date(session.startTime).toLocaleTimeString();

  // ADDED: "Target" field to match legacy functionality
  const header = `
================================================================
  LASTLOOK VERIFICATION REPORT
  ${dateStr}  |  ${timeStr}
================================================================

  SESSION DETAILS
  --------------------------------------------------------------
  Target:        ${session.destinationPath}
  Session ID:    ${session.sessionId}
  Machine:       ${session.machineName} (${session.os})
  App Version:   ${session.appVersion}

  SUMMARY
  --------------------------------------------------------------
  Status:        [✅ SUCCESS]
  Total Files:   ${files.length}
  Verified:      ${successCount} / ${files.length}
  Total Size:    ${formatSize(totalBytes)}
  Duration:      ${formatDuration(durationMs)}

  MANIFEST
  --------------------------------------------------------------
`;

  // 3. Format File List (The "Modern Tree")
  const body = files
    .map((file) => {
      // Determine status icon
      const statusIcon = file.status === "verified" ? "✅" : "❌";
      const sizeStr = formatSize(file.size_bytes);

      // OPTIONAL: We could add the time here too, but it might clutter.
      // Keeping it clean as per "Modern" design.
      return `  ${file.filename}
  └─ ${statusIcon} ${sizeStr.padEnd(10)} | Hash: ${file.hash_value} (${
        file.hash_type
      })
`;
    })
    .join("\n");

  // 4. Format Footer
  const footer = `
================================================================
  INTEGRITY SEAL: VALID
  Generated by LastLook v${session.appVersion}
================================================================
`;

  return header + body + footer;
}
